export const projects = [
  {
    id: 1,
    name: 'Website Redesign',
    description: 'Complete redesign of company website with modern UI/UX',
    status: 'in_progress',
    priority: 'high',
    owner: { id: 3, name: 'Sarah Johnson', role: 'manager' },
    team: [
      { id: 1, name: 'John Doe', role: 'developer' },
      { id: 2, name: 'Alice Smith', role: 'designer' },
      { id: 3, name: 'Sarah Johnson', role: 'manager' },
    ],
    startDate: '2024-01-15',
    endDate: '2024-04-30',
    deadline: '2024-04-30',
    progress: 65,
    budget: 50000,
    spent: 32500,
    department: 'IT',
    createdAt: '2024-01-10',
  },
  {
    id: 2,
    name: 'Mobile App Development',
    description: 'Native iOS and Android app for customer engagement',
    status: 'in_progress',
    priority: 'critical',
    owner: { id: 4, name: 'Mike Chen', role: 'manager' },
    team: [
      { id: 5, name: 'Emma Wilson', role: 'developer' },
      { id: 6, name: 'James Lee', role: 'developer' },
      { id: 4, name: 'Mike Chen', role: 'manager' },
    ],
    startDate: '2024-02-01',
    endDate: '2024-06-30',
    deadline: '2024-06-30',
    progress: 45,
    budget: 120000,
    spent: 54000,
    department: 'IT',
    createdAt: '2024-01-25',
  },
  {
    id: 3,
    name: 'HR System Implementation',
    description: 'Implementing new HRMS for better employee management',
    status: 'planning',
    priority: 'high',
    owner: { id: 7, name: 'Lisa Anderson', role: 'hr_manager' },
    team: [
      { id: 7, name: 'Lisa Anderson', role: 'hr_manager' },
      { id: 8, name: 'Robert Taylor', role: 'hr_manager' },
    ],
    startDate: '2024-05-01',
    endDate: '2024-08-31',
    deadline: '2024-08-31',
    progress: 15,
    budget: 80000,
    spent: 12000,
    department: 'HR',
    createdAt: '2024-02-10',
  },
  {
    id: 4,
    name: 'Cloud Migration',
    description: 'Migrate all services to cloud infrastructure',
    status: 'completed',
    priority: 'high',
    owner: { id: 3, name: 'Sarah Johnson', role: 'manager' },
    team: [
      { id: 1, name: 'John Doe', role: 'developer' },
      { id: 9, name: 'Chris Brown', role: 'developer' },
      { id: 3, name: 'Sarah Johnson', role: 'manager' },
    ],
    startDate: '2023-11-01',
    endDate: '2024-01-15',
    deadline: '2024-01-15',
    progress: 100,
    budget: 100000,
    spent: 98500,
    department: 'IT',
    createdAt: '2023-10-20',
  },
  {
    id: 5,
    name: 'Customer Support Platform',
    description: 'Building customer support ticketing system',
    status: 'in_progress',
    priority: 'medium',
    owner: { id: 10, name: 'David Martinez', role: 'manager' },
    team: [
      { id: 11, name: 'Nina Patel', role: 'developer' },
      { id: 12, name: 'Oliver Davis', role: 'developer' },
      { id: 10, name: 'David Martinez', role: 'manager' },
    ],
    startDate: '2024-03-01',
    endDate: '2024-05-31',
    deadline: '2024-05-31',
    progress: 55,
    budget: 60000,
    spent: 33000,
    department: 'IT',
    createdAt: '2024-02-15',
  },
];

export const tasks = [
  {
    id: 1,
    projectId: 1,
    title: 'Design homepage mockup',
    description: 'Create high-fidelity mockup for homepage',
    assignedTo: { id: 2, name: 'Alice Smith' },
    priority: 'high',
    status: 'completed',
    startDate: '2024-01-15',
    dueDate: '2024-01-25',
    duration: 10,
    progress: 100,
    subtasks: [
      { id: 1, title: 'Create wireframe', completed: true },
      { id: 2, title: 'Design visual hierarchy', completed: true },
      { id: 3, title: 'Get feedback from stakeholders', completed: true },
    ],
  },
  {
    id: 2,
    projectId: 1,
    title: 'Frontend development - Header',
    description: 'Develop header component with responsive design',
    assignedTo: { id: 1, name: 'John Doe' },
    priority: 'high',
    status: 'in_progress',
    startDate: '2024-01-26',
    dueDate: '2024-02-10',
    duration: 15,
    progress: 75,
    subtasks: [
      { id: 4, title: 'Create component structure', completed: true },
      { id: 5, title: 'Add responsive styles', completed: true },
      { id: 6, title: 'Add navigation links', completed: false },
      { id: 7, title: 'Test on mobile devices', completed: false },
    ],
  },
  {
    id: 3,
    projectId: 1,
    title: 'Backend API development',
    description: 'Develop REST API for website',
    assignedTo: { id: 1, name: 'John Doe' },
    priority: 'high',
    status: 'in_progress',
    startDate: '2024-02-01',
    dueDate: '2024-03-15',
    duration: 42,
    progress: 60,
    subtasks: [
      { id: 8, title: 'Setup database schema', completed: true },
      { id: 9, title: 'Create authentication endpoints', completed: true },
      { id: 10, title: 'Create content endpoints', completed: false },
    ],
  },
  {
    id: 4,
    projectId: 2,
    title: 'iOS app development',
    description: 'Develop iOS version of the app',
    assignedTo: { id: 5, name: 'Emma Wilson' },
    priority: 'critical',
    status: 'in_progress',
    startDate: '2024-02-01',
    dueDate: '2024-05-31',
    duration: 119,
    progress: 40,
    subtasks: [
      { id: 11, title: 'Setup Xcode project', completed: true },
      { id: 12, title: 'Design UI screens', completed: true },
      { id: 13, title: 'Implement features', completed: false },
      { id: 14, title: 'Testing & QA', completed: false },
    ],
  },
  {
    id: 5,
    projectId: 2,
    title: 'Android app development',
    description: 'Develop Android version of the app',
    assignedTo: { id: 6, name: 'James Lee' },
    priority: 'critical',
    status: 'in_progress',
    startDate: '2024-02-01',
    dueDate: '2024-05-31',
    duration: 119,
    progress: 50,
    subtasks: [
      { id: 15, title: 'Setup Android Studio project', completed: true },
      { id: 16, title: 'Design UI screens', completed: true },
      { id: 17, title: 'Implement features', completed: false },
      { id: 18, title: 'Testing & QA', completed: false },
    ],
  },
  {
    id: 6,
    projectId: 3,
    title: 'Requirements gathering',
    description: 'Gather requirements from stakeholders',
    assignedTo: { id: 7, name: 'Lisa Anderson' },
    priority: 'high',
    status: 'in_progress',
    startDate: '2024-05-01',
    dueDate: '2024-05-15',
    duration: 14,
    progress: 70,
    subtasks: [
      { id: 19, title: 'Schedule meetings with departments', completed: true },
      { id: 20, title: 'Document requirements', completed: true },
      { id: 21, title: 'Create specification document', completed: false },
    ],
  },
  {
    id: 7,
    projectId: 3,
    title: 'System design',
    description: 'Design HRMS system architecture',
    assignedTo: { id: 8, name: 'Robert Taylor' },
    priority: 'high',
    status: 'planning',
    startDate: '2024-05-16',
    dueDate: '2024-05-30',
    duration: 14,
    progress: 0,
    subtasks: [
      { id: 22, title: 'Create system architecture diagram', completed: false },
      { id: 23, title: 'Design database schema', completed: false },
      { id: 24, title: 'Define API specifications', completed: false },
    ],
  },
];

export const getProjectById = (id) => projects.find((p) => p.id === parseInt(id));
export const getTasksByProjectId = (projectId) => tasks.filter((t) => t.projectId === projectId);
export const getTaskById = (id) => tasks.find((t) => t.id === parseInt(id));
